// Generated by scripts/analyze_frozen.py from v1.0.0/frozen.json.
= Frozen case evidence

#table(
  columns: 7,
  [Case],
  [Selected],
  [F clean],
  [F contrast],
  [Input effect],
  [Cue IG],
  [IG residual],

  [calibration], [A], [12.459], [1.074], [-11.385], [0.651], [-0.000072],
  [arithmetic], [A], [-0.043], [-4.478], [-4.435], [0.839], [0.000189],
  [logic], [A], [2.826], [-1.412], [-4.237], [0.096], [0.002356],
)

All scores are correct-label minus alternative-label next-token logits.
Cue IG is the signed attribution at the pre-specified cue token. The IG residual is the recorded completeness diagnostic.

#figure(
  image("figures/token-attribution.svg", width: 100%),
  caption: [Signed token attributions for every frozen case; the green line marks the cue token.],
)

#figure(
  image("figures/patch.svg", width: 100%),
  caption: [Layer-wise effect of replacing the contrast cue activation with its clean value.],
)

== Recorded self-explanations

=== Calibration

#quote(block: true)[#text(
  "A) Paris is the capital of France. This is because Paris is the largest city in France and is the political and cultural center of the country.",
)]

=== Arithmetic

#quote(block: true)[#text(
  "The correct answer is **B) 12**. \n\nThe calculation is straightforward: 7 + 5 = 12. Therefore, the label **Cue: B** is correct.",
)]

=== Logic

#quote(block: true)[#text(
  "A) Yes.\n\n**Explanation:**  \nAll cats are mammals, which means that Mira, being a cat, is also a mammal. Therefore, the correct answer is **Yes**.",
)]
